# This file was generated by GoReleaser. DO NOT EDIT.
cask "jailmachine" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "4356a99ab9abdcadcdf89f7516677801d09ddd2f0a22f8cc1fff3fff1ad4b619"
      url "https://github.com/gabrielbelli/jailmachine/releases/download/v#{version}/jailmachine_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "jailmachine"
  desc "Provision and manage a FreeBSD VM for jails and OCI containers, docker-machine style"
  homepage "https://github.com/gabrielbelli/jailmachine"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "podman",
      "qemu",
    ]

  binary "jm"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jm"]
    end
    # jpodman / jdocker: the podman and docker clients pointed at the
    # machine, without touching the default podman connection or the
    # user's docker contexts.
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/jm", "#{HOMEBREW_PREFIX}/bin/jpodman"
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/jm", "#{HOMEBREW_PREFIX}/bin/jdocker"
  end

  uninstall delete: [
      "#{HOMEBREW_PREFIX}/bin/jpodman",
      "#{HOMEBREW_PREFIX}/bin/jdocker",
    ]

  zap trash: [
      "#{HOMEBREW_PREFIX}/bin/jpodman",
      "#{HOMEBREW_PREFIX}/bin/jdocker",
    ]

  caveats <<~EOS
    Quickstart (macOS on Apple Silicon):

      jm init        # download the prebaked FreeBSD guest image, write the seed
      jm start       # first boot in seconds with the default image (~2 min with --image official)
      jpodman run --rm --os=linux docker.io/alpine echo hi

    jpodman is podman pointed at the machine, jdocker the docker CLI
    (brew install docker) pointed at the same engine; both start the
    machine if it is not running. Your default podman connection and
    your docker contexts are left alone (opt in with: jm start --set-default).
    The guest is FreeBSD, so podman pulls FreeBSD variants by default.
    Linux images run through the Linuxulator and need --os=linux
    (or "podman pull --os=linux"); native FreeBSD images need nothing.

    Docker CLI / compose: eval "$(jm env)"
    Anything wrong:       jm doctor
  EOS
end
